function Hh= Hh(n,x)
function temp = temp (n,x)
    temp =(x+sqrt(x^2+4*n)/2)
end
Hh=sqrt((pi)/2^n)*exp(-(x^2)/2)*(hypergeom((n+1)/2,1/2,(x^2)/2)/(sqrt(2)*gamma(1+n/2)))-...
x*(hypergeom((n/2)+1/2,3/2,(x^2)/2)/(gamma((1+n)/2)))

if x>=-6 && x<10, Hh=(1/factorial(n))*integrate((t-x)^n*exp(-t^2/2),t,x,infinity)
else Hh=0,
    
    Hh=(1/factorial(n))*(integrate((t-x)^n*exp(-t^2/2),t,x,temp-3)+...
integrate((t-x)^n*exp(-t^2/2),t,temp-3,temp-1)+...
integrate((t-x)^n*exp(-t^2/2),t,temp-1,temp)+...
integrate((t-x)^n*exp(-t^2/2),t,temp,temp+1))+...
integrate((t-x)^n*exp(-t^2/2),t,temp+1,temp+3)+...
integrate((t-x)^n*exp(-t^2/2),t,temp+3,infinity)
end
end